version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5435:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=postgres